// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountTreeByEstateId mocks base method.
func (m *MockRepositoryInterface) CountTreeByEstateId(ctx context.Context, input CountTreeByEstateIdInput) (CountTreeByEstateIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTreeByEstateId", ctx, input)
	ret0, _ := ret[0].(CountTreeByEstateIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTreeByEstateId indicates an expected call of CountTreeByEstateId.
func (mr *MockRepositoryInterfaceMockRecorder) CountTreeByEstateId(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTreeByEstateId", reflect.TypeOf((*MockRepositoryInterface)(nil).CountTreeByEstateId), ctx, input)
}

// GetEstateById mocks base method.
func (m *MockRepositoryInterface) GetEstateById(ctx context.Context, input GetEstateByIdInput) (GetEstateByIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEstateById", ctx, input)
	ret0, _ := ret[0].(GetEstateByIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEstateById indicates an expected call of GetEstateById.
func (mr *MockRepositoryInterfaceMockRecorder) GetEstateById(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEstateById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEstateById), ctx, input)
}

// GetTreeHeightStats mocks base method.
func (m *MockRepositoryInterface) GetTreeHeightStats(ctx context.Context, input GetTreeHeightStatsInput) (GetTreeHeightStatsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreeHeightStats", ctx, input)
	ret0, _ := ret[0].(GetTreeHeightStatsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreeHeightStats indicates an expected call of GetTreeHeightStats.
func (mr *MockRepositoryInterfaceMockRecorder) GetTreeHeightStats(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreeHeightStats", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTreeHeightStats), ctx, input)
}

// GetTreesByEstateId mocks base method.
func (m *MockRepositoryInterface) GetTreesByEstateId(ctx context.Context, input GetTreesByEstateIdInput) ([]GetTreesByEstateIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreesByEstateId", ctx, input)
	ret0, _ := ret[0].([]GetTreesByEstateIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreesByEstateId indicates an expected call of GetTreesByEstateId.
func (mr *MockRepositoryInterfaceMockRecorder) GetTreesByEstateId(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreesByEstateId", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTreesByEstateId), ctx, input)
}

// InsertEstate mocks base method.
func (m *MockRepositoryInterface) InsertEstate(ctx context.Context, input CreateEstateInput) (CreateEstateOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEstate", ctx, input)
	ret0, _ := ret[0].(CreateEstateOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertEstate indicates an expected call of InsertEstate.
func (mr *MockRepositoryInterfaceMockRecorder) InsertEstate(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEstate", reflect.TypeOf((*MockRepositoryInterface)(nil).InsertEstate), ctx, input)
}

// InsertTree mocks base method.
func (m *MockRepositoryInterface) InsertTree(ctx context.Context, input CreateTreeInput) (CreateTreeOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTree", ctx, input)
	ret0, _ := ret[0].(CreateTreeOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTree indicates an expected call of InsertTree.
func (mr *MockRepositoryInterfaceMockRecorder) InsertTree(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTree", reflect.TypeOf((*MockRepositoryInterface)(nil).InsertTree), ctx, input)
}
